services:
  mysqldb:
    image: mysql/mysql-server
    container_name: jwt-database
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
  app:
    container_name: jwt-aplication
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    env_file: ./.env
    ports:
      - $PORT:$PORT
networks:
  database:
    external: true